### ISSUE TITLE
Handle nullable date.

### ISSUE THREAD

**Issue by GioPat** [probablykasper/date-picker-svelte#1] opened 2021-11-22 21:43 UTC
The library already allows null values, but when I pass to the DateInput I get this error:

![image](https://user-images.githubusercontent.com/9217515/142939382-41e02e5e-bd1f-4e91-961f-0b1743ba4c0f.png)

Is there any way to add an element that removes the date from the picker?
Asking this cause my date field is nullable.

**Comment by probablykasper** [comment] 2021-11-22 23:45
Null values are not allowed. The `value` argument can be `undefined` since it's optional, but the value itself can only be `Date`.

Not quite sure how this should be implemented 🤔 If `value` is `Date | null`, then I assume binding to a `Date` value wouldn't work.

**Comment by GioPat** [comment] 2021-11-22 23:47
Even with the undefined value, I can't manage to have an empty date

**Comment by probablykasper** [comment] 2021-11-22 23:53
The argument can be `undefined` since it's optional and defaults to `new Date()`, however the value cannot

**Comment by GioPat** [comment] 2021-11-23 17:38
Saw that the fallback of undefined is new Date(), in fact there is no way of having a null value for the input. How do you handle the case of a nullable date input field?

**Comment by probablykasper** [comment] 2021-11-23 18:46
Once again, the value cannot be null, there's no way for it to have a value other than `Date`. This is why I was wondering how to implement it.

**Comment by GioPat** [comment] 2021-11-23 22:16
I see that the value cannot be null. But I suppose the null can be implemented since the default html 5 input type date supports null value

**Comment by probablykasper** [comment] 2021-11-23 23:51
That's why I was wondering how to implement it. The HTML date input is not even a `Date` though, and it's null value is an empty string.

**Comment by GioPat** [comment] 2021-11-24 20:12
I suppose it can handled with the empty string.

**Comment by nimser** [comment] 2022-01-04 11:51
I think issue #3 is related to this.
Say you want to load the component without a date, showing the placeholder value of `-- / -- / ----`. Currently you can't do it, since the whole placeholder thing does not work and the component loads with a default `value` set to the current date (which happens [here](https://github.com/probablykasper/date-picker-svelte/blob/244b6c5f2ec8b0edbebd35b1b6b2a78390a8a7db/src/lib/DateInput.svelte#L29))

**Comment by mlandisbqs** [comment] 2022-02-10 23:34
would like to vote for this issue - this was a blocker my team to adopt this date picker component. otherwise it's the best one i've seen so far.

**Comment by mkelandis** [comment] 2022-02-11 16:42
Working on a PR for this - it's still a **draft** and needs some further tweaks, and regression and logging cleanup
https://github.com/mkelandis/date-picker-svelte/pull/1/files?diff=unified&w=1

**Comment by probablykasper** [comment] 2022-02-17 17:39
Fixed by #7

**Closed by probablykasper** 2022-02-17 17:39 UTC
