### ISSUE TITLE
Enable Time Input

### ISSUE THREAD

**Issue by MoritzHeld** [probablykasper/date-picker-svelte#36] opened 2022-12-03 18:44 UTC
Hey,

I discovered this nice library, but I wondered if you are able to activate the time picker function.
![image](https://user-images.githubusercontent.com/61581485/205456731-c15042bc-9296-411f-b50f-0edf2c6cadd1.png)
It would look like this..

Thanks in advance

**Comment by probablykasper** [comment] 2022-12-04 20:33
Duplicate of #4

**Closed by probablykasper** 2022-12-04 20:33 UTC
